# Generated by Django 4.2.2 on 2023-06-30 16:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Hackathon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("background_image", models.FileField(upload_to="images/")),
                ("hackathon_image", models.FileField(upload_to="images/")),
                (
                    "submission_type",
                    models.CharField(
                        choices=[
                            ("image", "image"),
                            ("file", "file"),
                            ("link", "link"),
                        ],
                        max_length=5,
                    ),
                ),
                ("start_datetime", models.DateTimeField(auto_now_add=True)),
                ("end_datetime", models.DateTimeField(auto_now=True)),
                ("reward_prize", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("summary", models.TextField(blank=True)),
                ("submission_file", models.FileField(upload_to="submissions/")),
                (
                    "hackthon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.hackathon"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
