# Generated by Django 4.1.7 on 2023-07-01 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_hackathon_registered_users"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hackathon",
            name="end_datetime",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="hackathon",
            name="start_datetime",
            field=models.DateTimeField(),
        ),
    ]
