# Generated by Django 4.2.2 on 2023-07-02 03:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app", "0004_alter_hackathon_end_datetime_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hackathon",
            name="registered_users",
            field=models.ManyToManyField(
                blank=True, default=[], to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
